// Generates TypeScript types and Go structs from schemas/*.schema.json.
// Usage: node scripts/generate.mjs
//
// Validation-only keywords (allOf/if/then/else/not) describe rules that cannot be expressed
// as a type. They stay in schemas/ for validators, and are stripped from a temporary copy
// that the code generators read.
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const banner = "DO NOT EDIT. Generated by scripts/generate.mjs from schemas/*.schema.json.";
const validationOnly = new Set(["allOf", "if", "then", "else", "not"]);

const strip = (node) => {
  if (Array.isArray(node)) return node.map(strip);
  if (node && typeof node === "object") {
    return Object.fromEntries(Object.entries(node).filter(([k]) => !validationOnly.has(k)).map(([k, v]) => [k, strip(v)]));
  }
  return node;
};

const tmp = mkdtempSync(join(tmpdir(), "rosetta-gen-"));
try {
  for (const f of readdirSync(join(root, "schemas")).filter((f) => f.endsWith(".schema.json"))) {
    const schema = JSON.parse(readFileSync(join(root, "schemas", f), "utf8"));
    writeFileSync(join(tmp, f), JSON.stringify(strip(schema), null, 2));
  }

  // TypeScript
  const ts = await compileFromFile(join(tmp, "index.schema.json"), {
    bannerComment: `/* ${banner} */`,
    unreachableDefinitions: true,
    additionalProperties: false,
    format: true,
    cwd: tmp,
  });
  mkdirSync(join(root, "src", "generated"), { recursive: true });
  writeFileSync(join(root, "src", "generated", "types.ts"), ts);

  // Go
  const files = ["ast", "component-definition", "warning", "position"].map((n) => join(tmp, `${n}.schema.json`));
  const goOut = join(tmp, "types_gen.go");
  execFileSync(
    "go",
    ["run", "github.com/atombender/go-jsonschema@v0.20.0", "-p", "contracts", "--only-models", "--tags", "json", "-t",
      "--capitalization", "URL", "-o", goOut, ...files],
    { stdio: ["ignore", "inherit", "inherit"] },
  );
  const go = readFileSync(goOut, "utf8").replace(/^\/\/ Code generated.*\n/m, "");
  writeFileSync(join(root, "types_gen.go"), `// ${banner}\n${go}`);
  execFileSync("gofmt", ["-w", join(root, "types_gen.go")]);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
console.log("generated src/generated/types.ts and types_gen.go");
