export const name = "@rosetta/editor";
export { createEditor, type EditorOptions } from "./editor";
export { standardExtensions } from "./extensions";
export { createToolbar, type ToolbarOptions } from "./toolbar";
export type { Editor } from "@tiptap/core";
export { fromAst, type LoadedDocument } from "./load";
export { Directive, DirectiveLeaf, componentsOf, newComponent } from "./directive";
export { createRegistry, type Definition, type Registry } from "./components/registry";
export { createForm, type Form, type FormValue } from "./components/form";
export type { RenderComponent } from "./components/render";
export type { ComponentOptions } from "./extensions";
export { toMarkdown, type SaveOptions } from "./save";
export { yamlMapping } from "./yaml";
