// DO NOT EDIT. Generated by scripts/generate.mjs from schemas/*.schema.json.

package contracts

type Attribute struct {
	// Default as the attribute's string form.
	Default *string `json:"default,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type AttributeType `json:"type"`

	// Allowed values when type is enum.
	Values []string `json:"values,omitempty"`
}

type AttributeType string

const AttributeTypeBoolean AttributeType = "boolean"
const AttributeTypeEnum AttributeType = "enum"
const AttributeTypeNumber AttributeType = "number"
const AttributeTypeString AttributeType = "string"

// Defines a component: its form, kind, attributes, fields and breakable flag (spec
// sections 4 and 9).
type ComponentDefinition struct {
	// Attributes corresponds to the JSON schema field "attributes".
	Attributes []Attribute `json:"attributes,omitempty"`

	// Required for data and container components. true: splits across columns and
	// pages. false: moves whole. Omitted for leaf components.
	Breakable *bool `json:"breakable,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Fields of a data component.
	Fields []Field `json:"fields,omitempty"`

	// Form corresponds to the JSON schema field "form".
	Form ComponentDefinitionForm `json:"form"`

	// data: YAML-style fields. container: Markdown body. leaf: no body.
	Kind ComponentDefinitionKind `json:"kind"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type ComponentDefinitionForm string

const ComponentDefinitionFormBlock ComponentDefinitionForm = "block"
const ComponentDefinitionFormLeaf ComponentDefinitionForm = "leaf"

type ComponentDefinitionKind string

const ComponentDefinitionKindContainer ComponentDefinitionKind = "container"
const ComponentDefinitionKindData ComponentDefinitionKind = "data"
const ComponentDefinitionKindLeaf ComponentDefinitionKind = "leaf"

// The Rosetta AST produced by the parser. Node is deliberately one flat shape
// discriminated by `type`, so that it maps cleanly to both TypeScript and Go.
type Document struct {
	// Children corresponds to the JSON schema field "children".
	Children []Node `json:"children"`

	// Preserved YAML front matter, if any.
	FrontMatter map[string]interface{} `json:"frontMatter,omitempty"`

	// The front matter text between the --- lines, exactly as written, so tools can
	// save it back unchanged. Present even when it is not valid YAML (then
	// frontMatter is absent).
	FrontMatterRaw *string `json:"frontMatterRaw,omitempty"`

	// Spec version the document was parsed as, for example 0.1.
	RosettaVersion string `json:"rosettaVersion"`

	// Warnings corresponds to the JSON schema field "warnings".
	Warnings []Warning `json:"warnings"`
}

type Field struct {
	// Default value; any JSON value.
	Default interface{} `json:"default,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Member fields when type is object.
	Fields []Field `json:"fields,omitempty"`

	// Item type when type is list. The name is ignored.
	Items *Field `json:"items,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// String fields only. When true the value is not read as Markdown.
	Plain *bool `json:"plain,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type FieldType `json:"type"`

	// Allowed values when type is enum.
	Values []string `json:"values,omitempty"`
}

type FieldType string

const FieldTypeBoolean FieldType = "boolean"
const FieldTypeEnum FieldType = "enum"
const FieldTypeList FieldType = "list"
const FieldTypeNumber FieldType = "number"
const FieldTypeObject FieldType = "object"
const FieldTypeString FieldType = "string"

type Node struct {
	// table.
	Align []NodeAlignElem `json:"align,omitempty"`

	// image.
	Alt *string `json:"alt,omitempty"`

	// directive: attribute values, always strings.
	Attributes map[string]string `json:"attributes,omitempty"`

	// directive: the text between the braces exactly as written (absent when there
	// were no braces), so it can be saved back unchanged, with shorthands, quotes and
	// mistakes as they were. A tool that changes the attributes must drop it.
	AttributesRaw *string `json:"attributesRaw,omitempty"`

	// directive: resolved breakable flag.
	Breakable *bool `json:"breakable,omitempty"`

	// Children corresponds to the JSON schema field "children".
	Children []Node `json:"children,omitempty"`

	// heading.
	Depth *int `json:"depth,omitempty"`

	// directive, data components: parsed YAML-style fields.
	Fields map[string]interface{} `json:"fields,omitempty"`

	// directive.
	Form *NodeForm `json:"form,omitempty"`

	// tableRow, true for the header row.
	Header *bool `json:"header,omitempty"`

	// directive: unknown when no component definition was found.
	Kind *NodeKind `json:"kind,omitempty"`

	// code.
	Lang *string `json:"lang,omitempty"`

	// directive: component name.
	Name *string `json:"name,omitempty"`

	// list.
	Ordered *bool `json:"ordered,omitempty"`

	// Position corresponds to the JSON schema field "position".
	Position *Position `json:"position,omitempty"`

	// directive: the raw body text. Always present for unknown components; for data
	// components it is the body as written, kept next to the parsed fields so it can
	// be saved back unchanged. A tool that changes a data component's fields must
	// drop it.
	Raw *string `json:"raw,omitempty"`

	// list, first number when ordered.
	Start *int `json:"start,omitempty"`

	// list: true when its items are not separated by blank lines (items render
	// without paragraphs).
	Tight *bool `json:"tight,omitempty"`

	// link, image.
	Title *string `json:"title,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type NodeType `json:"type"`

	// link, image.
	URL *string `json:"url,omitempty"`

	// text, inlineCode, code.
	Value *string `json:"value,omitempty"`

	// Warnings attached to this node.
	Warnings []Warning `json:"warnings,omitempty"`
}

type NodeAlignElem string

const NodeAlignElemCenter NodeAlignElem = "center"
const NodeAlignElemLeft NodeAlignElem = "left"
const NodeAlignElemNone NodeAlignElem = "none"
const NodeAlignElemRight NodeAlignElem = "right"

type NodeForm string

const NodeFormBlock NodeForm = "block"
const NodeFormLeaf NodeForm = "leaf"

type NodeKind string

const NodeKindContainer NodeKind = "container"
const NodeKindData NodeKind = "data"
const NodeKindLeaf NodeKind = "leaf"
const NodeKindUnknown NodeKind = "unknown"

type NodeType string

const NodeTypeBlockquote NodeType = "blockquote"
const NodeTypeBreak NodeType = "break"
const NodeTypeCode NodeType = "code"
const NodeTypeDirective NodeType = "directive"
const NodeTypeEmphasis NodeType = "emphasis"
const NodeTypeHeading NodeType = "heading"
const NodeTypeImage NodeType = "image"
const NodeTypeInlineCode NodeType = "inlineCode"
const NodeTypeLink NodeType = "link"
const NodeTypeList NodeType = "list"
const NodeTypeListItem NodeType = "listItem"
const NodeTypeParagraph NodeType = "paragraph"
const NodeTypeStrong NodeType = "strong"
const NodeTypeTable NodeType = "table"
const NodeTypeTableCell NodeType = "tableCell"
const NodeTypeTableRow NodeType = "tableRow"
const NodeTypeText NodeType = "text"
const NodeTypeThematicBreak NodeType = "thematicBreak"

type Point struct {
	// Column corresponds to the JSON schema field "column".
	Column int `json:"column"`

	// Line corresponds to the JSON schema field "line".
	Line int `json:"line"`

	// Offset corresponds to the JSON schema field "offset".
	Offset *int `json:"offset,omitempty"`
}

// A source range. Lines and columns are 1-based; offset is a 0-based byte offset.
type Position struct {
	// End corresponds to the JSON schema field "end".
	End Point `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start Point `json:"start"`
}

// A problem found while parsing or rendering. Never fatal: the affected part shows
// a visible warning and the rest of the document is unaffected (spec section 8).
type Warning struct {
	// Stable identifier, such as component.unknown or field.type.
	Code string `json:"code"`

	// Component name, if applicable.
	Component *string `json:"component,omitempty"`

	// Field or attribute name or path, such as traits[0].name.
	Field *string `json:"field,omitempty"`

	// Human-readable explanation.
	Message string `json:"message"`

	// Range corresponds to the JSON schema field "range".
	Range *Position `json:"range,omitempty"`

	// error when the affected part cannot render.
	Severity WarningSeverity `json:"severity"`
}

type WarningSeverity string

const WarningSeverityError WarningSeverity = "error"
const WarningSeverityWarning WarningSeverity = "warning"
